// Phone number scraping protection + sticky "Call Now" bar
// Generated by scripts/fix_phone_protection.py — see CLAUDE.md
// Vanilla JS (no jQuery dependency) so it works on every page, legacy or modern.
(function () {
  'use strict';

  function decodePhoneLinks() {
    var links = document.querySelectorAll('a[data-tel]');
    links.forEach(function (el) {
      var digits = el.getAttribute('data-tel').split('').reverse().join('');
      el.setAttribute('href', 'tel:' + digits);

      var formatted = '(' + digits.slice(0, 3) + ') ' + digits.slice(3, 6) + '-' + digits.slice(6);
      var nums = el.querySelectorAll('.phone-num');
      if (nums.length) {
        nums.forEach(function (n) { n.textContent = formatted; });
      } else if (!el.textContent.trim()) {
        el.textContent = formatted;
      }
    });
  }

  function initStickyCallBar() {
    var bar = document.getElementById('stickyCallBar');
    if (!bar) return;

    var SHOW_AFTER = 400;
    var ticking = false;

    function update() {
      var scrolled = window.scrollY || document.documentElement.scrollTop;
      var show = scrolled > SHOW_AFTER;
      bar.classList.toggle('is-visible', show);
      document.body.classList.toggle('sticky-call-active', show);
      ticking = false;
    }

    window.addEventListener('scroll', function () {
      if (!ticking) {
        window.requestAnimationFrame(update);
        ticking = true;
      }
    }, { passive: true });

    update();
  }

  document.addEventListener('DOMContentLoaded', function () {
    decodePhoneLinks();
    initStickyCallBar();
  });
})();
