
<?php 
/* Short and sweet */
define('WP_USE_THEMES', false);
require_once('./gd-blog/wp-blog-header.php');
?>
<!DOCTYPE html>

<!--[if IE 7]>                  <html class="ie7 no-js" lang="en">     <![endif]-->
<!--[if lte IE 8]>              <html class="ie8 no-js" lang="en">     <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> 
	<html class="not-ie no-js" lang="en">  <!--<![endif]-->

<head>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1" /> 

    <link rel="canonical" href="https://gdprowebdesigns.com/" >  
    <meta name="geo.region" content="US-MA" />
    <meta name="geo.placename" content="Everett" />
    <meta name="geo.position" content="42.40862; -71.05260" />
    <meta name="ICBM" content="42.40862; -71.05260" />
	 <meta name="robots" content="noodp">
     <meta name="robots" content="noydir">
	 <meta name="robots" content="index, follow">

	 <!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-N4P95M5');</script>
<!-- End Google Tag Manager -->

	<title>Freelance Website Designer Boston | Wordpress Developer | SEO + Marketing Services MA | GDWebPros</title>
	
	<meta name="description" content=" Boston Website Design and Development Company. We offer SEO Services, digital marketing services, Graphics Designer for small businesses"/>
	
	
	<meta name="keywords" content="Boston, Massachusetts, Web Design, Company, Wordpress, Developer, Freelance, SEO services, Digital Marketing, best graphic designer, Wordpress, designer. Android, IOS Apps.">
	
    
    
  <meta name="revisit-after" content="1 days" />
   	<meta name="robots" content="index, follow, noydir" />
   	<meta name="author" content="GDWebPros, Freelance Website Design Boston"/> 			
	<meta name="copyright" content="GDWebPros, Boston Web Designer"/>  	 	
	<meta name="distribution" content="global" />
	<meta name="resource-type" content="document" />
	<meta name="rating" content="General" />
	
	<!--Font Awesome--->
    	<!-- <link href="font-awesome/css/all.css" rel="stylesheet"> -->
	<!--Font Awesome End--->
		<link rel="stylesheet" href="assets/css/focus-style.css" media="screen" />
		<link rel="stylesheet" href="css/style.css">
        
        <link rel="stylesheet" href="css/feedback.css" media="screen" />
		<link rel="stylesheet" href="css/fancybox.min.css" media="all">

		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,300,800,700,400|PT+Serif:400" type="text/css" />
        
        <link href="https://fonts.googleapis.com/css?family=Gruppo&display=swap|Josefin+Sans:400,300,100|Josefin+Slab:100,300,400,600|Poiret+One|Quicksand:400,300,700" rel="stylesheet" type="text/css"/>
        
    
	<!--[if lte IE 6]>
		<link rel="stylesheet" href="//universal-ie6-css.googlecode.com/files/ie6.1.1.css" media="screen, projection">
	<![endif]-->

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "LocalBusiness",
  "name": "GDProWebDesigns",
  "image": "https://gdprowebdesigns.com/img/tmp-imgs/newlogo-gray-yellow-shadow2020.svg",
  "telephone": "(617) 771-0645",
  "address": {
    "@type": "PostalAddress",
    "streetAddress": "Lawrence St.",
    "addressLocality": "Everett",
    "addressRegion": "MA",
    "postalCode": "02149"
  },
  "openingHoursSpecification": {
    "@type": "OpeningHoursSpecification",
    "dayOfWeek": {
      "@type": "DayOfWeek",
      "name": "Monday, Tuesday, Wednesday, Thursday, Friday"
    },
    "opens": "09:30",
    "closes": "18:00"
  }
}
</script>

	<!-- HTML5 Shiv + detect touch events -->
	<script async src="js/modernizr.custom3.6.js"></script>
  
 <meta name="google-translate-customization" content="3b5a088a7f0933b5-b264fbfd05feeefa-g60b1aacdd87c2f7d-17"/>
	<!-- Clarity tracking code for http://gdprowebdesigns.com/ -->
	<script type="text/javascript">
    (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "5d537bdx7k");
</script>
          
</head>
<body>
	<!-- Google Tag Manager (noscript) -->
	<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-N4P95M5"
	height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
	<!-- End Google Tag Manager (noscript) -->
	<header id="header" class="container-fluid focus-bg"><!--clearfix-->
		<section id="animation" class="container align-center clearfix">
			<section id="main" class="focus"> 
			<div class="focus--mask">
			  <div class="focus--mask-inner">Check Out Our New Website</div>
			</div>
			</section>
			<section id="main2" class="align-center clearfix">
				<p> <a href="https://gdwebdesignma.com"  class="infobox2" title="Boston Freelance Website Designer & Wordpress Developer" target="_blank"> <span class="infobox2">www.GDWebPros.com</span></a>
				</p> 
			</section>
			
		</section>
		<div class=" container align-center">
			<a href="index.html" id="logo">
			<img src="img/tmp-imgs/newlogo-gray-yellow-shadow2020.svg" width="300" height="120" title="Freelance Wordpress Developer" alt="Boston Web Designer"></a>
				 <p><span class="infobox2"> Tel: <a href="tel:6177710645">617-771-0645</a> </span></p>
		</div>
	 <div class="container align-center"> 
		<nav id="main-nav"> <!--Removed from <nav class="clearfix">to test: class="clearfix" -->
			
			<ul>
					<li>
						<a href="index.php" title="Local Web Designer, Boston, Medford, Chelsea, Lynn MA" data-description="All starts here">Home</a></li>
						
					<li>
						<a href="boston-web-design-development-company-freelance.html" data-description="Web Design & Development">Services</a>
						<ul><li><a href="web-design-company-boston-ma.html"> Web Design</a></li>
							<li><a href="web-dsigner-developer-for-small-business-boston-ma.html">Web Development</a></li>
							<li><a href="graphics-designer-logos-boston.html">Graphic Design</a></li>
						</ul>
					</li>
						
						
						<li><a href="#" data-description="Promote your business">Marketing</a>
							<ul>
						<li><a href="organic-search-engine-optimization-boston.html">Search Engine Optimization</a></li>
								<li><a href="PPC-adwords-advertising-boston.html">Google Adwords Management</a></li>
						<li><a href="local-marketing-company-everett-malden-medford-revere-saugus-ma.html">Local Internet Marketing</a></li>
						
						 <li><a href="social-media-advertising.html">Social Media Integration</a></li>
								<li><a href="graphics-designer-logos-boston.html">Graphic Design</a></li>
							</ul>	</li>
					  
				 <!--End Web Services-->
				
		<li><a href="about-gd-freelance-web-designer-boston.html" title="Freelance Website Designer / Developer Boston MA" data-description="Local web developers">About US</a>
			<ul> <li><a href="blog.html" data-description="recent news">Blog</a></li></ul>
				
				</li>
					
				
				<li>
					<a href="portfolio-website-design-development-boston-ma.html" title="Freelance Web Developer Chelsea, Everett, Malden, Medford, Somerville MA" data-description="Work we are proud of">Portfolio</a>
					<ul>
					  <li><a href="portfolio-website-design-development-boston-ma.html">Web Design &amp; Development</a></li>
						<li><a href="portfolio-graphics-design-boston-everett-ma.html">Graphic Designs</a></li>
					</ul>
				</li>
				<li>
					<a href="contact-gd-website-design-estimates.php" title="Contact affordable freelance web designers" data-description="Enquire here">Contact GD</a>
				</li>
			   
			</ul>
	
		</nav>
		<!-- end #main-nav --></div>
	
		
	</header><!-- end #header -->

<section class="container clearfix">
	<header class="align-center"> 
	<h1 class="section-title mt-small"> Boston Website Design Company. Freelance </h1>
	<p class="slogan">We can help your small business with any <b>Front End or Back End Web Development.</b><br>
		<span style="font-size: small;"> &lt; HTML, CSS, SASS, PHP, JAVASCRIPT, JQUERY, REACT &#47;&gt;</span><br>
 	e-Commerce (Shopping cart) Website Design & Development. <br>
	 Custom Wordpress Theme Development, or Customize a pre-built HTML or Wordpress website template, Etc. </p>

	  	<div class="one-half small-align-center"> 
	   		<a href="inicio.html" class="button no-bg" title="Programador de Paginas Web Boston MA" target="_blank"><mark>Hablamos Espa&ntilde;ol</mark></a>
		</div><!-- end .infobox -->
	   
    	<div class="one-half last align-center">
		<a href="portfolio-website-design-development-boston-ma.html" title="Boston  Web Designer" class="button no-bg align-right">
				<mark>Check Our  Work </mark> <img src="img/tmp-imgs/icon-grid.png" alt="Boston Web Design &amp; Development" class="icon">
  		</a><!-- end .infobox -->
		</div>

   
 	<div class="clear"></div> 

		<hr>
   <div class="container align-center clearfix"> 
	   <h2 class="title align-center">Hire Frelance Web Designer in Boston, MA.
   </h2><p class="slogan"> <a href="https://gdwebdesignma.com" target="_blank" title="Freelance Web Developer Boston, MA">@GDWebPros</a> is a freelance web designer in Boston, with 15+ years of experience working with Wordpress, Shopify, Wix, Weebly, Etc.<br> Based in Everett and near Boston, MA!</p>
   Call For Free Consultation  @:<a href="tel:6177710645" style="font-size: 2em!important;" title="Freelance Website Designer"> (617) 771-0645</a>
	   
	</div>
	<hr>
   </header>
	
<div class="align-center">
	<h2>Why Hire <a href="https://www.facebook.com/GDWebpros/" target="_blank">@GDWebPros</a>?</h2>
	<p class="slogan"> If You Own a <span class="color">Small Business in Massachusetts, </span><br>
      don't Have a Large Budget, but <br>
   
   Need a Professional Website for Your Small Business, Designed & Developed by a website design pro, <br>
You are at The Right Place!</p>
<p>Affordable and professional freelance website Designers ready to bring your ideas to life and your website ready to show up on Google Search Results.  </p>
<p> We offer Wordpress custom responsive website designs or Wordpress theme customization. Static HTML web design and development and professional graphics design, logo design.</p><p> But more importantly we have more than 15 years of experience optimizing websites with organic SEO (Search Engine Optimization) services.  </p>
    <h3>Website Design & SEO Services Go Hand and Hand.</h3> 
	<mark>(There's no successful website without proper organic SEO, unless you have a large budget for Google PPC Advertising!!)</mark>
</div>
	
<p>Located in <a href="https://g.page/r/CY2l1DPJt5fMEBM/" target="_blank" title="Dise&ntilde;ador Web Everett, MA" class="color">Everett, MA,</a> we serve nearby cities like <a href="chelsea-ma-disenador-web-wordpress.html" title="Dise&ntilde;o paginas web Wordpress Chelsea, MA" class="color">Chelsea,</a> <a href="boston-web-design-development-company-freelance.html" title="Dise&ntilde;o &amp; Desarrollo Web East Boston, MA" class="color">East Boston,</a> <a href="revere-ma-servicios-de-diseno-web-wordpress.html" title="Dise&ntilde;o Sitios Web" class="color">Revere,</a><a href="somerville-ma-web-designer.html" title="Ayuda con Wordpress Somerville, MA" class="color"> Somerville,</a> <a href="malden-web-designer-wordpress-developer.html" title="Diseno de Sitios Web y Dise&ntilde;o Grafico" class="color"> Malden,</a> <a href="lynn-ma-disenador-sitios-web-wordpress.html"  title="Dise&ntilde;ador Paginas Web Lynn, MA" class="color">Lynn,</a> <a href="saugus-web-designer-wordpress-developer-seo.html" title="Dise&ntilde;o Paginas Web Profesional" class="color">Saugus,</a> <a href="medford-website-design-company-wordpress-developer.html" title="Dise&ntildeo y Desarrollo Sitios Web con Wordpress, Wix, Shopify" class="color">Medford,</a> <a href="#" class="color">Charlestown, Winchester, Etc.</a> We have also built websites for companies in Los Angeles California, Oregon, New York, and more.
	</p>
	
	
	<div class="align-center">
	<h3 class="color"><a href="contact-gd-website-design-estimates.html">Ask A Website Design Pro a Question!</a></h3>
	</div>
	<br></br>
   
	
	<!--<div class="notice"><h3><strong>Let's Start .</strong></h3></div>-->
	
	<div id="main_home">
		<div class="image-gallery-slider">  
			<h2>Our Web Design & Development Services</h2> 
        <ul class="projects-carousel clearfix">
			<li>
				<img src="img/web-design/freelance-web-designer-boston-ma-200x165.webp" width="200" height="165" loading="lazy" class="single-image" alt="Wordpress Developer, Design Help Boston">
				<h5 class="title">Website Design and Development</h5>
				<p>Custom website design and development. <br><mark>Responsive website design.</mark> We follow the mobile first approach.</br> Customize a pre-built website template, instead of custom web design.<br> We can help with any <strong> website design and development </strong> or finish up the one you started building on Wix, Shopify or Wordpress. <strong><a href="tel:6177710645">Just call:  (617) 771-0645</a></strong> <br>
				We are freelance web developers, helping small companies get results. </span> <a href="web-design-company-boston-ma.html" class="small">more about web design</a></li>

				<li>
						<img src="img/other-web-services/thumbnails/freelance-wordpress-developer-220x165.webp" width="200" height="165" loading="lazy" alt="Wordpress Developer, Design Help Boston">
				<h5 class="title">Custom Wordpress Theme Development</h5>
				<span ><mark>Custom Wordpress web design </mark>can get expensive.<br> Why don't use a <mark>pre-built WordPress theme</mark> and customize it to fit your content and services? <br><strong>We can help!!</strong><br> We have more than 17 years of experience building websites for small businesses, with SEO in mind. <strong><a href="tel:6177710645">Just call:  (617) 771-0645</a></strong> <br>
				We are freelance web developers in Boston, helping small companies get results. </span><a href="wordpress-developer-boston-ma.html" class="small">more about wordpress</a></li>

				<li>
					<img src="img/seo-services/SEO-services-boston-220x165.webp" width="200" height="165" loading="lazy" alt="Organic SEO Company Boston, MA">
					
				<h5 class="title">Organic SEO Services Boston, MA</h5>
				<span><mark>Drive more organic traffic to your website.</mark><br> We optimize your website to show up in search engine results like Google, Bing, Yahoo.<br> Increase traffic to your website.<br> Generate more leads and get more sales with organic SEO services in Boston, MA</span><a href="organic-search-engine-optimization-boston.html" class="small">more about SEO</a>
				</li>
				
				<li>
				<img src="img/other-web-services/thumbnails/freelance-seo-service-boston-ma-200x165.webp"  width="200" height="165" loading="lazy"  alt="Freelance Search Engine Optimization">
	  			<h5 class="title">Local SEO Marketing Services</h5>
				<span>Local businesses show up on <mark>Google, Yahoo and/or Bing Maps</mark> organic results for  searches around your business location.<br> We make sure to address  "on page" and "off page" factors that affect your rankings on local search results.</span><a href="local-marketing-company-everett-malden-medford-revere-saugus-ma.html" class="small"> more about marketing</a></li>

				<li>
				<img src="img/other-web-services/thumbnails/freelance-seo-service-boston-ma-200x165.webp" width="200" height="165" loading="lazy"  alt="Freelance Search Engine Optimization">
	  			<h5 class="title">Google Ads/PPC Advertising Management </h5>
				<span>Improve your ROI with PPC marketing.</span><a href="local-marketing-company-everett-malden-medford-revere-saugus-ma.html" class="small"> more about marketing</a></li>

				
				<li>
					<img src="img/other-web-services/thumbnails/social-media-integration-200x165.webp" width="200" height="165" loading="lazy" alt=" Social Media Integration, Digital Marketing, Boston MA">	
				<h5 class="title"> Integrate Social Media to Your Business Website</h5>
				<span >We customize social media business pages:  FaceBook, Twitter, Linked In, Youtube, Instagram and other social media sites. Reach more clients, promote your business for free!</span><a href="social-media-advertising.html" class="small">more about social media</a>
				</li>

			<li>
					<img src="img/other-web-services/thumbnails/digital-media-marketing-social-media-marketing-200x165.webp" width="200" height="165" loading="lazy" alt="Social Media marketing for small business">
					<h5 class="title">Promote Your Business on Youtube | Video Editing,  Photo Retouch</h5>
				<span>We retouch your photos or create beautiful videos for your business! We even take the pictures for your website!</span><a href="#"  class="small">learn more</a></li>	
		</ul>
		<!-- end .projects-carousel -->
		<h3> Hire Affordable Wordpres Web Designer and Developer in Boston, MA</h3>
		<p>We are a small web design service in Everett, MA; Located just three miles from downtown Boston, we understand small business and tight budgets.</p>
		</div>
		
	</div>
	 
    <section id="creative" class="container">
		<div class="align-center">
	<h2 class="color"><a href="contact-gd-website-design-estimates.html">Our Website Design Process</a></h2>
	</div>

	<ul class="projects-carousel clearfix">

	  <li class="align-center mbpadding">
		<!-- <img src="img/web-design/web-design-consultation.png" alt="Boston Web Designer Services">-->
		  <i class="fas fa-people-arrows fa-5x  mbpadding"></i>

	    <h5 class="title"> Free Web Design Consultation</h5>
	 
		  <ol class="text-left">
			  <li><strong>We gather information:</strong><br>
 				Put YOUR ideas and our ideas to work.</li>
			  <li><strong>Gather content: </strong><br>
				images (We offer <a href="https://www.facebook.com/jaarmira/">Photography</a> Services if needed), Content writing.</li>
		  </ol>
		   <span class="categories"><a href="web-design-company-boston-ma.html" title="Web Design And Development" target="_blank">Bring The Ideas</a> </span>
		</li>
       
      <li class="align-center mbpadding">
			
			<!--<img src="img/web-design/creative-web.png" alt="Boston Responsive Web Designer">-->
			<!-- <i class="far fa-lightbulb fa-5x mbpadding"></i>-->
		  <i class="fas fa-magic fa-5x mbpadding"></i>
		<h5 class="title">Start Web Design </h5>
		 
		  <ol class="text-left"><li><a href="boston-web-design-development-company-freelance.html"> Web Design</a></li>
			  <li><a href="graphics-designer-logos-boston.html">Logo Design</a></li>
			  <li><a href="https://facebook.com/jaarmira">Photography or graphics for your website.</a></li>
			  <li><a href="graphics-designer-logos-boston.html">Collateral Printing: brochures, menus, etc.</a></li> </ol>
		  
			 <span class="categories"><a href="boston-web-design-development-company-freelance.html">Design Process</a> </span>
		
       </li>

		<li class="align-center mbpadding">
			<i class="fas fa-code fa-5x  mbpadding"></i>
	   <h5 class="title">Start Web Developmet</h5>
			
		  
			<p class="text-left"> Depending on the complexity of your project, we will suggest the best  Content Management System (CMS):<a href="wordpress-developer-boston-ma.html"> Wordpress</a> Joomla or another you feel more confortable with. Magento, Woocommerce, or any other for your ecommerce project.  </p>
			<span class="categories"><a href="web-dsigner-developer-for-small-business-boston-ma.html">We start Coding.</a> </span>
		</li>  
			<li  class="align-center mbpadding">
				<i class="fas fa-search-dollar fa-5x  mbpadding"></i>
	  <h5 class="title">Marketing (SEO)</h5>
	
	<ol class="text-left"><li><a href="organic-search-engine-optimization-boston.html">Search Engine Optimization</a></li>
		 <li><a href="PPC-adwords-advertising-boston.html">PPC (Pay Per Click)</a></li>
		 <li><a href="social-media-advertising.html">Social Media Marketing</a></li></ol>
	<p class="text-left"> Not every website is on first page of Google, we can make it happen for your business!</p>
	<span class="categories"><a href="organic-search-engine-optimization-boston.html">Let's Promote Your Business</a> </span>
     <!-- <a href="organic-search-engine-optimization-boston.html" class=""  title="Freelance SEO Company Boston"> Start Marketing</a> -->
	</li> 
  </ul>
	
	</section>
	<h2 class="align-center">Remember! <br>If You Need More Clients <br><a href="organic-search-engine-optimization-boston.html">You Need Marketing.</a> </br><br>A Website Alone Won't Do It!  </h2> </br>

  <h5 class="section-title">On a Tight Budget? </h5>
<h3> Affordable SEO & Internet Marketing Services in Boston, MA</h3>
	 <p> We offer affordable responsive web design services and web development. We can build your business website with html5 (static website), design and develop a custom WordPress theme, or  use a pre built Wordpress template/theme. We can further customize your Wix, SquareSpace, Shopify or other platform website, if custom web design and development is out of your budget.</p>
	 <p> We know small business don't have a big budget, but having a professional website designed is very important!! <br>
				As freelance web designers, we know we can design a professional website without the high prices of a stablished website design company in Boston, MA. We can help!!</p> 
	<p>Email us to <a href="contact-gd-website-design-estimates.html" title="Web Design Consultation"><mark>Schedule a Quick Web Design Consultation</mark></a></p>

	<ul class="post-carousel">

		<li>
			<div class="entry-meta">

				<a href="#">
					<span class="post-format">&nbsp;</span>
				</a>

				<span class="date"></span>

			</div><!-- end .entry-meta -->

			<div class="entry-body">

				
					<h3> Boston Freelance Web Designer</h3>
				

			  <p>We build responsive (mobile friendly) websites with HTML5, Wordpress, Joomla, Wix, Weebly, Shopify or other web platform. We understand small screens and Small Businesses too!</p>
                 
                <a href="boston-web-design-development-company-freelance.html" title="Mobile website developer Everett, Malden, Medford MA" class="small">about Us </a>
					
			</div><!-- end .entry-body -->

		</li>

		<li>

			<div class="entry-meta">

				
					<a href="#"><span class="post-format gallery">Social Media</span></a>
				

				<span class="date"></span>

			</div><!-- end .entry-meta -->

			<div class="entry-body">

				
					<h3>Social Media Marketing for Small Business</h3>
					
					
              <p>GD Pros has the knowledge and experience to integrate your business to Social Media Apps...</p>
                    <a href="social-media-advertising.html" title="Promote your business in social media Boston"  class="small"> more about marketing</a>
				
 
			</div><!-- end .entry-body -->

		</li>

		<li>
			

			<div class="entry-meta">

				<a href="#">
					<span class="post-format video">You tube</span>
				</a>

				<span class="date"></span>

			</div><!-- end .entry-meta -->

			<div class="entry-body">

				
					<h3>You tube Video Editing </h3>
<p>
 
 Promote your company on You-tube.	if you do not know how, give GD Pros a call and let us give you a hand with your internet marketing needs.</p>
 <a href="local-marketing-company-everett-malden-medford-revere-saugus-ma.html" class="small">more internet marketing</a>
			</div>
            
            
            
		</li>
			  <!-- end .entry-body -->
		  
	  

		<li>

			<div class="entry-meta">

				<a href="#">
					<span class="post-format link">You tube </span>
			</a></div><!-- end .entry-meta -->

			<div class="entry-body">
					<h3>Visit us on Facebook!</h3>

			  <p>Free  online marketing is always good when you are a startup business. Include social media in your internet marketing, create a business page on Facebook and other social media sites.</p>
              
              <a href="https://www.facebook.com/pages/GD-Pro-Web-Designs/113091575402539" title="Social media integration" class="small" target="_blank">Us on Facebook</a>
              
               
  </div><!--end .entry-body -->
 					
		</li>  
	</ul> <!-- end .post-carousel -->
	
	<!--Start logos carousel --->
	
	<ul class="projects-carousel clearfix">



		<li>

			<a href="/wordpress-developer-boston-ma.html">

				<img src="img/web-development/software/wordpress-cms-small.png" width="220" height="140" loading="lazy" alt="Custom Wordpress Design and Web Development">

				<h5 class="title">Wordpress</h5>



			</a>

		</li>



		<li>

			<a href="/wordpress-developer-boston-ma.html">

				<img src="img/web-development/software/woocommerce-logo.png" width="220" height="140" loading="lazy" alt="Woommerce development logo">

				<h5 class="title">Woocommerce</h5>



			</a>

		</li>



		<li>

			<a href="#">

				<img src="img/web-development/software/Laravel_logo.png" width="220" height="140" loading="lazy" alt="Freelance Web Developer Boston, MA">

				<h5 class="title">Laravel</h5>

			<!-- <span class="categories">animation / illustration</span> -->

			</a>

		</li>



		<li>

			<a href="#">

				<img src="img/web-development/software/magento-logo.png" width="220" height="140" loading="lazy" alt="Magento e-Commerce developer Boston, MA">

				<h5 class="title">Magento</h5>

<!--		<span class="categories">web / animation</span>-->

			</a>

		</li>



		<li>

			<a href="#">

				<img src="img/web-development/software/Shopify_Logo.png" width="220" height="140" loading="lazy" alt="Shopify design help">

				<h5 class="title">Shopify</h5>

<!--				<span class="categories">illustration / photography</span>-->

			</a>

		</li>



		<li>

			<a href="#">

				<img src="img/web-development/software/squarespace-logo-small.png" width="220" height="140" loading="lazy" alt="SquareSpace Design Help Boston, MA">

				<h5 class="title">SquareSpace</h5>

<!--				<span class="categories">photography</span>-->

			</a>

		</li>



		<li>

			<a href="#">

				<img src="img/web-development/software/JQuery-logo.png"  width="220" height="140" loading="lazy" alt="jQuery">

				<h5 class="title">jQuery</h5>

<!--				<span class="categories">illustration / web / animation</span>-->

			</a>

		</li>



		<li>

			<a href="#">

				<img src="img/web-development/software/html5-logo.png" width="220" height="140" loading="lazy" alt="Html5 Static Websites Design">

				<h5 class="title">HTML</h5>

<!--				<span class="categories">illustration / design</span>-->

			</a>

		</li>
		<li>

			<a href="#">

				<img src="img/web-development/software/javascript-web-development-computer-programming-220.png" width="220" height="140" loading="lazy" alt="javascript developer Boston, MA">

				<h5 class="title">Javascript</h5>

<!--		<span class="categories">web / animation</span>-->

			</a>

		</li>

	</ul><!-- end .projects-carousel -->
	
</section>  <!-- end #content -->

<footer id="footer" class="clearfix">

	<div class="container">

		<div class="three-fourth">

			<nav id="footer-nav" class="clearfix">

				<ul>
					<li><a href="index.html" title="Local Web Designer, Boston, Medford, Chelsea, Lynn MA">Home</a></li>
					<li><a href="web-design-company-boston-ma.html" title="Freelance Website Designer, Everett, Boston, Lynn, Sommerville MA">Website design</a></li>
					
					<li><a href="portfolio-website-design-development-boston-ma.html" title="Graphic Designer Everett, Chelsea, Lynn MA">Portfolio</a></li>
					<li><a href="contact-gd-website-design-estimates.html" title="Free Web or Graphic Design quotes, Lynn, Boston, Everett MA">Contact</a></li>
					<li><a href="blog.html">Recent News</a></li>
                    <li><a href="sitemap.html">Site map</a></li>
				</ul>
				
			</nav><!-- end #footer-nav -->

			<ul class="contact-info">
				<li class="address"> Boston Massachusetts. Professional Design &amp; Development   Services in the USA</li>
				<li class="phone">(617) 771-0645</li>
				<li class="email"><a href="contact-gd-website-design-estimates.html" target="_blank">Get a quote or ask for a free consultation   here</a></li>
			</ul><!-- end .contact-info -->
			
		</div><!-- end .three-fourth -->

		<div class="one-fourth last">

			<span class="title">Stay in touch</span>

			<ul class="social-links">
            
				<li class="linkedin"><a href="http://www.linkedin.com/company/gd-pro-web-designs?trk=top_nav_home" title="Web and Graphic Designer Boston, Everett, Medford, Chelsea, Somerville MA" target="_blank">Linked in</a></li>
				<li class="twitter"><a href="#" title="Follow GD Pro on Twiter" target="_blank">Twitter</a></li>
				<li class="facebook"><a href="https://www.facebook.com/pages/GD-Pro-Web-Designs/113091575402539" title="Social Media Integration Boston, Everett, Chelsea, Medford, Somerville, MA" target="_blank">Facebook</a></li>
				
				<li class="youtube"><a href="http://www.youtube.com/user/silfovientoful" title="Video Editing, Everett, Local Advertising Boston" target="_blank">You Tube</a></li>
				<li class="googleplus"><a href="https://plus.google.com/+JaArmira" title="Freelance Web Developer/Designer Boston, Everett, Medford, Chelsea, Lynn MA" target="_blank">Google Plus</a></li>
			</ul><!-- end .social-links -->

		</div><!-- end .one-fourth.last -->
		
	</div><!-- end .container -->

</footer><!-- end #footer -->

<footer id="footer-bottom" class="clearfix">

	<div class="container">

		<ul>
			<li>GD ProWebDesigns &copy; Since 2005</li>
			<li><a href="#">Legal Notice</a></li>
			<li><a href="#">Terms</a></li>
		</ul>

	</div><!-- end .container -->

</footer><!-- end #footer-bottom -->

<!--[if !lte IE 6]><!-->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="js/jquery-1.7.1.min.js"><\/script>');</script>
  
	<!--[if lt IE 9]> <script src="js/selectivizr-and-extra-selectors.min.js"></script> <![endif]-->
	<!-- <script defer src="fontawesome/js/all.js"></script> -->
	<script  src="js/respond.min.js"></script>
	<script  src="js/jquery.easing-1.3.min.js"></script>
	<script  src="js/jquery.fancybox.pack.js"></script>
	<script  src="js/jquery.smartStartSlider.min.js"></script>
	<script  src="js/jquery.jcarousel.min.js"></script>
	<script  src="js/jquery.cycle.all.min.js"></script>
	<script  src="js/jquery.isotope.min.js"></script>
	
	<script async src="js/jquery.touchSwipe.min.js"></script>
	<script  src="js/custom.js"></script>
 
    
    
</body>
</html>